dataset:
  value: SUN
num_class:
  value: 717
num_attribute:
  value: 102
img_size:
  value: 448
resnet_region:
  value: 196
dim_f_clip:
#  value: 2048
  value: 768
dim_v_clip:
  value: 768
device:
  value: cuda:0
batch_size:
  value: 50
epochs:
  value: 200
#  value: 400
use_unzip:
  value: True
random_seed:
  value: 6

lambda_cal:
  value: 0.01
lambda_reg:
  value: 0.1
lambda_con:
  value: 0.7

normalize_V:
  value: False
tf_SAtt:
  value: False
tf_ec_layer:
  value: 1
tf_dc_layer:
  value: 1
tf_heads:
  value: 1

tf_clip_common_dim:
  value: 128
tf_aux_embed:
  value: False
tf_dim_feedforward:
  value: 2048
tf_dropout:
  value: 0.3